# Generated by Django 6.0.3 on 2026-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importantdate',
            name='emoji',
            field=models.CharField(choices=[('🎂', "Tug'ilgan kun"), ('📅', 'Uchrashuv'), ('💰', "To'lov"), ('🎉', 'Bayram'), ('💍', "To'y"), ('📝', 'Imtihon'), ('🏥', 'Doctor'), ('⭐', 'Boshqa')], default='⭐', max_length=10),
        ),
        migrations.AlterField(
            model_name='importantdate',
            name='type',
            field=models.CharField(choices=[('birthday', "Tug'ilgan kun"), ('meeting', 'Uchrashuv'), ('payment', "To'lov"), ('holiday', 'Bayram'), ('wedding', "To'y"), ('exam', 'Imtihon'), ('doctor', 'Doctor')], max_length=20),
        ),
    ]
