# Generated by Django 6.0.3 on 2026-07-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
