# Generated by Django 6.0.3 on 2026-07-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_expense_title'),
    ]

    operations = [
    ]
