# Generated by Django 6.0.3 on 2026-07-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LifeHub', max_length=100)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('force_ssl', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('telegram_notifications', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
