# Generated by Django 4.2.30 on 2026-07-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner',
            field=models.ImageField(blank=True, help_text='Sayt banneri', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Instagram havoli', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Sayt logotipi', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_channel',
            field=models.URLField(blank=True, help_text='Telegram kanal havoli', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_link',
            field=models.URLField(blank=True, help_text='TikTok havoli', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube havoli', null=True),
        ),
    ]
